name: Daily Trigger SPX Webhook

on:
  schedule:
    - cron: '30 13 * * 1-5'  # UTC時間 13:30 = 美東時間 09:30 = 溫哥華 06:30
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Webhook
        run: curl -s -X GET "https://spx-webhook.onrender.com/trigger"
