on:
  schedule:
    - cron: '30 13 * * 1-5'   # 美东时间 09:30（开盘策略）
    - cron: '00 17 * * 1-5'   # 美东时间 13:00（中盘策略）
    - cron: '30 19 * * 1-5'   # 美东时间 15:30（收盘策略）
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Webhook
        run: curl -s -X GET "https://spx-webhook.onrender.com/trigger"
