on:
  schedule:
    - cron: '45 13 * * 1-5'   # 06:45 PST
    - cron: '30 16 * * 1-5'   # 09:30 PST
    - cron: '00 19 * * 1-5'   # 12:00 PST
    - cron: '45 22 * * 1-5'   # 15:45 PST
  workflow_dispatch:

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call /trigger endpoint
        run: curl -s https://spx-webhook.onrender.com/trigger
