name: Daily Trigger SPX Webhook

on:
  schedule:
    - cron: '0 13 * * 1-5'  # 每週一到五，PDT 時間早上 6 點
  workflow_dispatch:        # 手動觸發

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send /trigger request
        run: |
          curl -s https://spx-webhook.onrender.com/trigger
